/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_centerix_zverus_zverus_ZverusNative */

#ifndef _Included_ru_centerix_zverus_zverus_ZverusNative
#define _Included_ru_centerix_zverus_zverus_ZverusNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_Login__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    Register
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_Register
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    Login
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_Login__
  (JNIEnv *, jclass);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    LogOut
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_LogOut
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    GetLoginId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_GetLoginId
  (JNIEnv *, jclass);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    GetLoginName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_GetLoginName
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    GetLoginError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_GetLoginError
  (JNIEnv *, jclass);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    AddContact
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_AddContact
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    GetContacts
 * Signature: ()[Lru/centerix/zverus/zverus/ZverusContact;
 */
JNIEXPORT jobjectArray JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_GetContacts
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    GetContact
 * Signature: (Ljava/lang/String;)[Lru/centerix/zverus/zverus/ZverusContact;
 */
JNIEXPORT jobjectArray JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_GetContact
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    GetChats
 * Signature: ()[Lru/centerix/zverus/zverus/ZverusContact;
 */
JNIEXPORT jobjectArray JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_GetChats
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    GetChatsUpd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_GetChatsUpd
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    GetMessages
 * Signature: (I)[Lru/centerix/zverus/zverus/ZverusMessage;
 */
JNIEXPORT jobjectArray JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_GetMessages
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    GetMessagesUpd
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_GetMessagesUpd
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    SendMessage
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_SendMessage
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    NativeNmea
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_NativeNmea
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusNative
 * Method:    NativeInitAndroidId
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_centerix_zverus_zverus_ZverusNative_NativeInitAndroidId
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
