/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_centerix_zverus_zverus_ZverusActivity */

#ifndef _Included_ru_centerix_zverus_zverus_ZverusActivity
#define _Included_ru_centerix_zverus_zverus_ZverusActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_Login__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    Register
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_Register
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    Login
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_Login__
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    LogOut
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_LogOut
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    GetLoginId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_GetLoginId
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    GetLoginName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_GetLoginName
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    GetLoginError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_GetLoginError
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    AddContact
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_AddContact
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    GetContacts
 * Signature: ()[Lru/centerix/zverus/zverus/ZverusContact;
 */
JNIEXPORT jobjectArray JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_GetContacts
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    GetContact
 * Signature: (Ljava/lang/String;)[Lru/centerix/zverus/zverus/ZverusContact;
 */
JNIEXPORT jobjectArray JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_GetContact
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    GetChats
 * Signature: ()[Lru/centerix/zverus/zverus/ZverusContact;
 */
JNIEXPORT jobjectArray JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_GetChats
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    GetChatsUpd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_GetChatsUpd
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    GetMessages
 * Signature: (I)[Lru/centerix/zverus/zverus/ZverusMessage;
 */
JNIEXPORT jobjectArray JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_GetMessages
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    GetMessagesUpd
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_GetMessagesUpd
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    SendMessage
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_SendMessage
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    NativeNmea
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_NativeNmea
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    Test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_Test
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    Test2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_Test2
  (JNIEnv *, jobject);

/*
 * Class:     ru_centerix_zverus_zverus_ZverusActivity
 * Method:    NativeInitAndroidId
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_centerix_zverus_zverus_ZverusActivity_NativeInitAndroidId
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
